project:
  type: book

number-depth: 2

#title-block-banner: '#C6D4FB'
#title-block-banner-color: '#333333'

book:
  title: "Developable Land Inventory"
  subtitle: "Technical Guidance"
  chapters:
    - index.qmd
    - outputs.qmd
    - stat_def.qmd
  page-footer: "CT GIS Office, July 2026 V1.0"

#bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt

editor: visual

