project:
  type: book

number-depth: 2

toc: true
toc-depth: 5

book:
  title: "Developable Land Inventory"
  author: "CT Office of Policy and Management, GIS Office"
  subtitle: "Technical Guidance"
  chapters:
    - index.qmd
    - intro.qmd
    - outputs.qmd
    - stat_def.qmd
    - vac_redev.qmd
    - map.qmd
    - end.qmd
  page-footer: "CT GIS Office, July 2026 V1.0"
  favicon: CT-GIS-Office-favicon.png
  downloads: [pdf]
  sidebar:
    logo: 'opm_giso_logo.png'

format:
  html:
    theme:
      - brand
      - cosmo
    linkcolor: "#1F64E5"
    include-in-header:
      text: |
        <script>
          document.addEventListener("DOMContentLoaded", function() {
            var sidebar = document.getElementById('quarto-sidebar');
            var logo = sidebar.getElementsByTagName('img')[0];
            
            sidebar.appendChild(logo);
          });
        </script>
  pdf:
    documentclass: scrreprt
    mainfont: Arimo
    sansfont: Poppins
    #pdf-standard: ua-2
    keep-tex: true
    
    include-before-body: cover.tex
    
    include-in-header:
      text: |
        \usepackage{booktabs}
        \usepackage{array}
        \usepackage{graphicx}
        \usepackage{xcolor}
        \usepackage{eso-pic}

        \renewcommand{\arraystretch}{1.2}
        
        \AtBeginDocument{\let\maketitle\relax}

    
editor: visual

